export const ACTIONS = {
  GET_NOTES_STARTED: "GET_NOTES_STARTED",
  GET_NOTES_SUCCESS: "GET_NOTES_SUCCESS",
  GET_NOTES_ERROR: "GET_NOTES_ERROR",
  GET_NOTE_STARTED: "GET_NOTE_STARTED",
  GET_NOTE_SUCCESS: "GET_NOTE_SUCCESS",
  GET_NOTE_ERROR: "GET_NOTE_ERROR",
  CREATE_NOTE_STARTED: "CREATE_NOTE_STARTED",
  CREATE_NOTE_SUCCESS: "CREATE_NOTE_SUCCESS",
  CREATE_NOTE_ERROR: "CREATE_NOTE_ERROR",
  EDIT_NOTE_STARTED: "EDIT_NOTE_STARTED",
  EDIT_NOTE_SUCCESS: "EDIT_NOTE_SUCCESS",
  EDIT_NOTE_ERROR: "EDIT_NOTE_ERROR",
  DELETE_NOTE_STARTED: "DELETE_NOTE_STARTED",
  DELETE_NOTE_SUCCESS: "DELETE_NOTE_SUCCESS",
  DELETE_NOTE_ERROR: "DELETE_NOTE_ERROR",
};

export const API = "http://localhost:5000";
